### ISSUE TITLE
HTTP 404 is raised

### ISSUE THREAD

**Issue by daudrain** [AntoineAugusti/radars-france#1]
It looks like the endpoint used by the code is not valid anymore:
```
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    radars = do_request(endpoint('all'))
  File "main.py", line 26, in do_request
    r.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://radars.securite-routiere.gouv.fr/all?_format=json
```

**Comment by AntoineAugusti** [comment]
They changed the endpoint. https://github.com/AntoineAugusti/radars-france/commit/43bc99c7fff0583e0fd0c32e98096b91b2a4195a should fix it
